base_config: configs/replica/replica.yaml

exp_name: replica/office4

data_specs:
  data_path: '../Datasets/Replica/office4'
  max_depth: 10
  use_gt: True

decoder_specs:
  # [x_min,x_max],[y_min,y_max],[z_min,z_max]
  # nice-slam's bound + [10,10,10]
  bound: [ [ 6.3, 17.8 ],[ 5.2, 16.7 ],[ 6.3, 14.1 ] ] # nice-slam's bound + [10,10,10]
