base_config: configs/replica/replica.yaml

exp_name: replica/office2

data_specs:
  data_path: '../Datasets/Replica/office2'
  max_depth: 10
  use_gt: True

decoder_specs:
  # [x_min,x_max],[y_min,y_max],[z_min,z_max]
  # nice-slam's bound + [10,10,10]
  bound: [ [ 5. , 14.6 ],[ 5.6, 16.9 ],[ 7.2, 13.1 ] ] # nice-slam's bound + [10,10,10]
