base_config: configs/replica/replica.yaml

exp_name: replica/office0

data_specs:
  data_path: '../Datasets/Replica/office0'
  max_depth: 10
  use_gt: True

decoder_specs:
  # [x_min,x_max],[y_min,y_max],[z_min,z_max]
  # nice-slam's bound + [10,10,10]
  bound: [ [ 4.5, 15.9 ],[ 3.3, 15.4 ],[ 5.3, 15.3 ] ] # nice-slam's bound + [10,10,10]

