base_config: configs/replica/replica.yaml

exp_name: replica/office1

data_specs:
  data_path: '../Datasets/Replica/office1'
  max_depth: 10
  use_gt: True

decoder_specs:
  # [x_min,x_max],[y_min,y_max],[z_min,z_max]
  # nice-slam's bound + [10,10,10]
  bound: [ [ 4.7, 16.5 ],[ 4.9, 16. ],[ 5.5, 15.2 ] ] # nice-slam's bound + [10,10,10]
