base_config: configs/scannet/scannet.yaml

exp_name: scannet/scene0181

data_specs:
  data_path: '../Datasets/scannet_data/scene0181_00'
  depth_scale: 1000.0
  crop: 6
  scale_factor: 0
  use_gt: True
  max_depth: 5

decoder_specs:
  bound: [ [ 9.0,18.9 ],[ 9.1,18.0 ],[ 9.0,13.6 ] ] # nice-slam's bound + [10,10,10]