base_config: configs/scannet/scannet.yaml

exp_name: scannet/scene0059

data_specs:
  data_path: '../Datasets/scannet_data/scene0059_00'
  depth_scale: 1000.0
  crop: 12
  scale_factor: 0
  use_gt: True
  max_depth: 5

decoder_specs:
  bound: [ [ 9.1,17.3 ],[ 9.0,19.6 ],[ 9.0,13.7 ] ] # nice-slam's bound + [10,10,10]